apiVersion: v1
kind: Service
metadata:
  namespace: geth
  name: geth-rpc
spec:
  ports:
    - name: rpc
      targetPort: rpc
      port: 80
  selector:
    app: geth
---
apiVersion: v1
kind: Service
metadata:
  namespace: geth
  name: geth-auth-rpc
spec:
  ports:
    - name: auth-rpc
      targetPort: auth-rpc
      port: 80
  selector:
    app: geth
---
apiVersion: v1
kind: Service
metadata:
  namespace: geth
  name: geth-p2p
spec:
  type: NodePort
  ports:
    - name: p2p-tcp
      targetPort: p2p-tcp
      port: 30303
      nodePort: 30303
      protocol: TCP
    - name: p2p-udp
      targetPort: p2p-udp
      port: 30303
      nodePort: 30303
      protocol: UDP
  selector:
    app: geth
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: geth
  name: chaindata
spec:
  storageClassName: blockchain-storage
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      # Note: Obviously in reality this would be more like 1-2 Terabytes
      storage: 100Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth
  namespace: geth
spec:
  serviceName: "geth"
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /debug/metrics/prometheus
        prometheus.io/port: "6060"
      labels:
        app: geth
    spec:
      nodeSelector:
        name: nodes
      securityContext:
        fsGroup: 65000
      containers:
        - name: geth
          image: 320786661812.dkr.ecr.eu-central-1.amazonaws.com/poc/geth:v1.13.3
          ports:
            - containerPort: 8545
              name: rpc
            - containerPort: 8551
              name: auth-rpc
            - containerPort: 30303
              name: p2p-tcp
              protocol: TCP
            - containerPort: 30303
              name: p2p-udp
              protocol: UDP
            - containerPort: 6060
              name: metrics
          volumeMounts:
            - name: jwt-shared
              readOnly: true
              mountPath: /opt/ethereum/shared
            - name: chaindata
              mountPath: /opt/ethereum/execution
      volumes:
        - name: jwt-shared
          secret:
            secretName: jwt-shared
        - name: chaindata
          persistentVolumeClaim:
            claimName: chaindata