apiVersion: v1
kind: Secret
metadata:
  namespace: geth
  name: jwt-shared
stringData:
  jwt.hex: "SETME"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: prysm
  name: jwt-shared
stringData:
  jwt.hex: "SETME"