{
 "title": "Prysm",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(p2p_peer_count,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Current, justified, and finalized epochs. In this order, these three values should be sequentially decreasing.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(beacon_clock_time_slot{job=\"kubernetes-pods\",instance=~\"$instance\"} / 32)",
     "legendFormat": "current"
    },
    {
     "expr": "beacon_current_justified_epoch{job=\"kubernetes-pods\",instance=~\"$instance\"}",
     "legendFormat": "justified"
    },
    {
     "expr": "beacon_finalized_epoch {job=\"kubernetes-pods\",instance=~\"$instance\"} ",
     "legendFormat": "finalized"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_slot{job=\"kubernetes-pods\",instance=~\"$instance\"}",
     "legendFormat": "current slot"
    },
    {
     "expr": "beacon_head_slot{job=\"kubernetes-pods\",instance=~\"$instance\"}",
     "legendFormat": "head slot"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "The percentage of ETH balances expected to attest that are actually attesting.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Participation Rate" }
   ],
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"kubernetes-pods\",instance=~\"$instance\"} / beacon_prev_epoch_active_gwei{job=\"kubernetes-pods\",instance=~\"$instance\"} )",
     "legendFormat": "participation rate"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "description": "Number of beacon nodes to which this node is connected.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"kubernetes-pods\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "stat",
   "description": "The percentage of ETH balances expected to attest that are actually attesting.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"kubernetes-pods\",instance=~\"$instance\"} / beacon_prev_epoch_active_gwei{job=\"kubernetes-pods\",instance=~\"$instance\"} )"
    }
   ]
  },
  {
   "title": "Network Liveness",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((floor(beacon_clock_time_slot{job=\"kubernetes-pods\",instance=~\"$instance\"}/32) - beacon_finalized_epoch{job=\"kubernetes-pods\",instance=~\"$instance\"} - 2)/100))),0)"
    }
   ]
  },
  {
   "title": "Network Validators",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Validator Queues",
   "type": "stat",
   "description": "Current number of pending and exiting validators",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",job=\"kubernetes-pods\",instance=~\"$instance\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",job=\"kubernetes-pods\",instance=~\"$instance\"}",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Validator Counts",
   "type": "stat",
   "description": "Counts of active, slashed and exited validators.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Active\",job=\"kubernetes-pods\",instance=~\"$instance\"} ",
     "legendFormat": "active"
    },
    {
     "expr": "validator_count{state=\"Slashed\",job=\"kubernetes-pods\",instance=~\"$instance\"} ",
     "legendFormat": "slashed"
    },
    {
     "expr": "validator_count{state=\"Exited\",job=\"kubernetes-pods\",instance=~\"$instance\"} ",
     "legendFormat": "exited"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "description": "Number of pending and existing validators over time. Pending validators are shown as positive values, while exiting validators are shown as negative values.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "validators" }
   ],
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",job=\"kubernetes-pods\",instance=~\"$instance\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",job=\"kubernetes-pods\",instance=~\"$instance\"}",
     "legendFormat": "exiting"
    },
    {
     "expr": "validator_count{state=\"Slashing\",job=\"kubernetes-pods\",instance=~\"$instance\"}",
     "legendFormat": "slashing"
    },
    {
     "expr": "validator_count{job=\"kubernetes-pods\",instance=~\"$instance\", state=\"Active\"}",
     "legendFormat": "active validators"
    }
   ]
  },
  {
   "title": "Queue Lengths",
   "type": "stat",
   "description": "Estimated length of time until all pending and exiting validators have cleared the queues.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((validator_count{state=\"Pending\",job=\"kubernetes-pods\",instance=~\"$instance\"}/6)*6.4)",
     "legendFormat": "pending"
    },
    {
     "expr": "((validator_count{state=\"Exiting\",job=\"kubernetes-pods\",instance=~\"$instance\"}/6)*6.4)",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Avg. Balance",
   "type": "stat",
   "description": "Average validator balance across the network",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\",job=\"kubernetes-pods\",instance=~\"$instance\"} / validator_count{state=\"Active\",job=\"kubernetes-pods\",instance=~\"$instance\"} / 1000000000",
     "legendFormat": "eth"
    }
   ]
  },
  {
   "title": "Client Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers to which the beacon chain is connected",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"kubernetes-pods\",instance=~\"$instance\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Process Uptimes",
   "type": "stat",
   "description": "The length of time the beacon chain and validator processes have been running.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"kubernetes-pods\",instance=~\"$instance\"})/3600",
     "legendFormat": "beacon chain"
    },
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator\"})/3600",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Prysm Versions",
   "type": "table",
   "description": "Versions of the currently running Prysm clients.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "max(prysm_version) by (version)"
    }
   ]
  },
  {
   "title": "Beacon Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{job=\"kubernetes-pods\",instance=~\"$instance\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{job=\"kubernetes-pods\",instance=~\"$instance\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  }
 ]
}